### PR TITLE
Changes to takename space from  in_message_name automatically and out…

### PR DESCRIPTION
**Pull request by tynarasimhareddy**

### CODE REVIEW

**Comment by tynarasimhareddy** [comment]
This is the initial change to provide option to specify the name space for each API and accept the request.
And corrected the out_message_name parsing when namespace is provided in the rpc call.
WSDL issue is still there. I will continue working on this.

**Comment by plq** [comment]
this needs tests. otherwise, it looks fine.

**Comment by plq** [comment]
many thanks for the pull request by the way.

**Comment by tynarasimhareddy** [comment]
Where to add the tests? could you please guide me on adding the same.

**Comment by plq** [comment]
As this is an interface test, spyne/test/interface is going to be your main target. This patch will need to test both XML Schema generation and WSDL generation so depending on the nature of your patches you will have to add tests to both test_xml_schema.py and wsdl/test_wsdl_ports_services.py

It's easy for me to move them around once you send them, so if you just use common sense and put them in a sensible location, I can take it from there.

**Comment by plq** [comment]
This aside, I see you removed multi_ns flag from Application. Because of the backwards-compatibility promise, we need to be absolutely sure that old behavior doesn't change unless explicitly wanted by the user. Some people could be unknowingly reliant on app.tns being hardcoded. So I say it's best to bring it back.

**Pull request merged**
